### ISSUE TITLE
[Review & Testing] Adding the landing page to the course

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#101]
Opening a new issue for this as this is to be discussed with Asim, the project team and LF, not Osama.

This is the feedback I got from LF on adding the landing page url to the course. None of the options seem ideal imo. TBD.

Regarding leading users to your own landing page - the 'exit course' button at the very end cannot be used - that is a platform-level feature that cannot be tweaked. There are two options to do this:
1) Add a standalone course page with text and link that opens in a separate tab taking learners to your landing page. This page would be placed anywhere before the final exam - you would need to indicate the placing.
2) Add message and link on the final exam Congratulations message (see [this screenshot](https://drive.google.com/file/d/1_NA7xMqAJTskgIQhHF6849gzb1T8J57Q/view?usp=sharing)). The drawback in this instance is that it may be missed, as there is a lot on this page.

UPDATE: you may review the entire course [here](https://docs.google.com/presentation/d/1QJLv_tPb6dx1jXxIUwJqaXLqhEFvsb_u7qiODwoWhkc/edit)

**Comment by holanita** [comment]
LF just asked that we _share the text (and link) we would like to see taking learners to our landing page. Then they can play with the exact text and see what can be done_. 
@jawache let me know if you have something in mind and/or let's discuss in the call tomorrow.

**Comment by jawache** [comment]
So I think we take both, one page just before exam AND a link at the end.

Page before exam should ask them to
-  join our newsletter
- local meetup group
- community of green software people on Discotd

Link after exam

Take them to a page which has links for diff orgs, so if thoughtworks want to track who has passed the exam, they create their own form and we say if you are from TW you use that form. It can be a page on our site. That way we avoid and GDPR issues.

**Comment by holanita** [comment]
@jawache as discussed, [here is a draft copy for each scenario](https://docs.google.com/document/d/1qzmJmHH2tJ0yYuiGPBenLlcgNoUM4V9uoa2Cmw79bxY/edit?usp=sharing). Please review and edit as you see fit.

**Comment by holanita** [comment]
Reviewed. Copy to be shared with the LF later today.

**Comment by holanita** [comment]
ATM 1) is done; **2) waiting for LF**; 3) done; 4) not possible. See details in the google doc.

**Comment by holanita** [comment]
2) is not possible either.
