### ISSUE TITLE
[AFTER COP] Promote the course to orgs / org leads

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#103]
Why: to maximize the number of people who complete the course
What: promote the course to orgs / org leads after cop so they can share the course with their own people

TBD: if we can offer something to orgs to motivate them / how to generate stats by organisations

**Comment by holanita** [comment]
TBD in our upcoming call with Asim & Namrata tomorrow.

**Comment by holanita** [comment]
As per our latest discussions with Asim, we will focus our marketing efforts on SOGS. The course has not been included in our marketing calendar as per his request. TBD how to handle the course especially given our ambitious target.

**Comment by holanita** [comment]
Briefly discuss with Tammy today in the team call. TBD tomorrow in the Community WG call as well.

**Comment by holanita** [comment]
We haven't started promoting the course to org leads yet (as we are focusing on SOGS as per Asim's request), however BCG, Accenture and Microsoft have already created forms to register their employees who completed the course. See [here](https://docs.google.com/document/d/1Jv-f7wGyODzEySQFfVk6Vo_OAHWjf-jAdFmyfDQUgvU/edit?usp=sharing).

**Comment by jawache** [comment]
@holanita might I suggest this. The course will be one of our long term goals for 2023 (I'm  still honestly going to target 1 million devs!), but right now any asks to companies should be around SoGS (interviews, surveys etc...).

So let's pause this for now and come back in Jan. Some ideas for when we return.
- Review how/if Accenture integrated the course into their corp training website, get a doc together explaining how they did it so we can send to other companies and teach them how to do the same.
- Maybe for the above do a press release, just focusing on Accenture - see if we get any press from this, Accenture will co-promote that a lot with us.
- For Earth Day next year perhaps have an online event where we get as many people to complete the course and share their certificate online. "Green Software Day", get the Community Working Group involved, that's just the kind of activity that works for them. Not like an event where we have people speaking, but just like a moment in time.
- Let's explore getting the training in other catalogs, like Udemy (I'm an author there, actually I have about 50k students on my other courses I sell on there so this should defo be an approach).
- Reach out to Carbon Disclosure Project and try to get them to add this as a question on the disclosure form they send to companies, if we can convince CDP to do this, we've achieved our goal in one go)

**Comment by holanita** [comment]
Okay, I assume we can put this on hold for now and revisit in a few months @jawache but do let me know if you don't agree.

**Comment by holanita** [comment]
@jawache sorry, ignore my previous message. At first I thought we would only do the Earth Day Live Banner and not the ones you listed in bullet. I'll start mapping out tasks for all of them a bit later.
