### ISSUE TITLE
[Website] Add a "Take the exam" button to Training website

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#108]
Why: the training page does not contain any reference to the actual online training
What: Sarah we should have a button somewhere on the training page which points to the online training 

Next steps:
- [x] @holanita to share the url of the online training once the training went live
- [x] @jawache to confirm where exactly to put this button (maybe add some context, text, etc?)
- [x] @osamajandali to add the button once everything is confirmed

Related issue: https://github.com/Green-Software-Foundation/training/issues/89

**Comment by holanita** [comment]
@zanete can you help me figure out if this is something Osama and Asim could start working on while we are waiting for the course to go live and the url to be confirmed? (also, let me know if I added this task the right way to Osama's board)

**Comment by zanete** [comment]
@holanita Thank you, the issue is appearing correctly on Osama's board can you confirm the urgency of this? Osama will be focusing on the Speakers website this week and SoGS website next week, which means that he will not be able to do this by the milestone set for this issue and realistically, unless we change priorities for him, the implementation could be done some time in the w/c 7th of November. Will that be an issue?

**Comment by holanita** [comment]
Thanks for the insights @zanete I think this will be fine. We can add the link to the online course anywhere in the text if needed. I'm still waiting for LF to provide the url of the online course. ETA next Tuesday.

**Comment by zanete** [comment]
Great stuff, I will put it as blocked on the WEB board until there is that URL.

**Comment by zanete** [comment]
The idea here is to do it the same way as done for the Pattern website to keep consistent as it is outlined here: https://github.com/Green-Software-Foundation/ops-content/issues/8 @holanita will that be ok?

**Comment by holanita** [comment]
@zanete okay with me. this idea comes from Asim and Sarah, so you might need to ask Asim too.

**Comment by zanete** [comment]
@holanita ok, good to know, do you have meetings with them to review other things about this project to run this past them? or should I reach out individually?

**Comment by holanita** [comment]
@zanete ah sorry I just thought it would be easier for you to get a reply from Asim. added this to our weekly meeting agenda.

**Comment by zanete** [comment]
@holanita thanks! I save that privilege for very urgent blocking issues 😆

**Comment by holanita** [comment]
@zanete @osamajandali the course is now live, you can proceed
- this is the url: https://training.linuxfoundation.org/training/green-software-for-practitioners-lfc131/
- we need to change the wording as this is not a certification. instead of 'get certified' can you put 'take the course'

**Comment by zanete** [comment]
@osamajandali FYI, i've swapped this one with https://github.com/Green-Software-Foundation/ops-content/issues/8 as this is higher priority, so as soon as State of Green Software website is done, please proceed onto this 🙏

**Comment by holanita** [comment]
@zanete @osamajandali when you have the catchup meeting today, please discuss whether this is doable for cop. if not, we need to find another way to help people get to the course from our website. if we send people to our website during cop, but there is not link to the course, this will kill conversions.

**Comment by osamajandali** [comment]
It's done check it out on the website header

**Comment by holanita** [comment]
@osamajandali perfect thank you! :)

can you make it stand out more so people find it easily? maybe make it bold and use a different color (one from our color palette or the blue from the target website)? if this is too much, feel free to ignore my ask and close this as is. thanks.

**Comment by osamajandali** [comment]
@holanita done

**Comment by jawache** [comment]
Actually @osamajandali can we change the name again, "take the course" isn't obvious what it means, since you are already looking at a "course".

"Get a certificate of completion"

or 

"Take the exam"

@holanita can we make a short link so we can track the number of people who head to LF training from our training, maybe grnsft.org/practitioner/lf-exam and @osamajandali can you use that shortlink instead so we can easily track the traffic we are sending.

**Comment by holanita** [comment]
@jawache sure grnsft.org/practitioner/lf-exam sounds good to me. I don't know how to create that short link though.

**Comment by zanete** [comment]
I've created the link: https://grnsft.org/practitioner/lf-exam now points to https://training.linuxfoundation.org/training/green-software-for-practitioners-lfc131/ and 
@osamajandali please use the short one: https://grnsft.org/practitioner/lf-exam with text "Take the exam" 
(i picked the shorter one, buttons with long text don't look natural)

**Comment by holanita** [comment]
This looks perfect, thanks a lot @osamajandali
