### ISSUE TITLE
[Reference] Energy Efficiency: PUE

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/training#11]
Link power usage effectiveness to a good external definition, paper, maybe the original report from the Green Grid.

https://github.com/Green-Software-Foundation/training/blob/755ac252ae024be0c334cca2aaebade5d22d467b/docs/practitioner/energy-efficiency.md?plain=1#L61

**Comment by greenhsu123** [comment]
How about- https://www.thegreengrid.org/en/resources/library-and-tools/237-PUE%3A-A-Comprehensive-Examination-of-the-Metric ?

**Comment by holanita** [comment]
https://datacenters.lbl.gov/sites/default/files/WP49-PUE%20A%20Comprehensive%20Examination%20of%20the%20Metric_v6.pdf
