### ISSUE TITLE
Reorganize training website to host the current course only

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#111]
**Why**: Asim mentioned yesterday that there will not be more courses any time soon
**What**: we should make some adjustments on the website so that this site would be about the current course only

One thing that is missing is a page that could serve as a proper landing page for the current training. Right now everyone lands either on the generic page (which is too broad for the current course) or on the intro page of the course (which is weird as some context would be required before starting with the intro page). My suggestion would be to:

- rename the main page in the left menu so it's called 'Green Software Practitioner' not 'Learning Green Software'
- reword the content on this page a bit to mention the current course specifically
- rename the second menu item on the left from 'Green Software Pracitioner' to something like 'Chapters' (note that this link has no page behind it, it's only used to open up the chapters!)

This is either something that Asim will quickly do himself once he made a decision. If not, we will still need his input first.

**Comment by holanita** [comment]
@jawache please advise

**Comment by holanita** [comment]
@jawache @zanete please advise / help

**Comment by zanete** [comment]
@holanita thank you, I will catch up about this with @jawache tomorrow and will keep you updated.

**Comment by zanete** [comment]
@holanita Asim will do all training website things Friday morning. Can we double check that this was also discussed with the team and that they would be happy with such a change? @jawache is saying he could send an email but I'm not sure when he'd be able to do this, so perhaps that is something you could take on and arrange a consensus with the team before Friday morning?

**Comment by holanita** [comment]
@zanete this ticket was included in the agenda of our team meeting held yesterday. I explained the idea briefly and the team didn't have any objections. those who did not attend will also be able to see this in the agenda. is this ok?

**Comment by jawache** [comment]
Similar to #89 pull request created.

**Comment by holanita** [comment]
@jawache there might be a misunderstanding here. #89 is a different story. 

this ticket here is about the website that is visible to public. something went wrong after the updates. we have welcome twice in the menu. see [here](https://drive.google.com/file/d/1nStzT7yZdRjRJxlM_KbWituo6DnprrMu/view?usp=share_link).

**Comment by zanete** [comment]
@osamajandali, @jawache says he has spent a long time on this but can't figure out why the welcome is showing twice and that if you get a chance before COP to take a look, that would be highly appreciated. Let's discuss today
cc @holanita

**Comment by holanita** [comment]
Great this looks perfect 👍
