### ISSUE TITLE
Add new logo to training / principles page

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#114]
Why: to make sure we use the most up-to-date logo on the website
What: Osama to pick and upload the right logo format from the ones we have [on the drive](https://drive.google.com/drive/folders/1xFcZ5YBFctzI75Nsdl7VOGwklTYd_WYj)

@zanete can you find the right sprint for this depending on Osama's availability and current tasks

**Comment by zanete** [comment]
We'll discuss this next Monday, but from what I can see, given the priority, it would be post-COP

**Comment by osamajandali** [comment]
So as far as I understand, principles are the same as training. I use the principle logo here, right?

**Comment by holanita** [comment]
@osamajandali yes, you can use the one from [this folder](https://drive.google.com/drive/folders/1xFcZ5YBFctzI75Nsdl7VOGwklTYd_WYj)

**Comment by zanete** [comment]
@holanita are you happy with this task?

**Comment by holanita** [comment]
@zanete the logo in the top right corner looks great thanks. can we replace the logo in the favicon as well just like for the other websites?

**Comment by zanete** [comment]
@holanita it's updated, just need to do a hard refresh, if you're on mac it would be cmd+shift+R

**Comment by holanita** [comment]
@zanete awesome thanks I'm closing this :)
