### ISSUE TITLE
[AFTER COP] Promote the course in external channels

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#117]
Why: to create visibility and boost course completion outside the GSF network
What: to be discussed with Namrata and Asim how we can build this into our campaigns

**Comment by holanita** [comment]
Hi @NAMRATA-WOKE the Linux Foundation will start promoting our course after COP. 

This is what they have planned:
- Right now they have a blog post that will go up on their website on November 11. 
- They have social media content prepared to go out through the rest of the month - on Twitter, Instagram & Facebook. 
- They also send social content internally to all their employees and invite them to share on their personal profiles.

They are asking if they should tag any of our social media when these things go live. 
- So shall I share the links to our Twitter, Instagram, Facebook (unsure if we have them all)?
- Do you want them to use any hashtags?

**Comment by NAMRATA-WOKE** [comment]
@holanita can you share the blog post and social media content they've planned? Visibility would be nice. 
Yes - they can tag GSF on Twitter and LinkedIn:
Twitter: @gsfcommunity 
LinkedIn: Green Software Foundation 

Request they use #greensoftware in their posts.

**Comment by holanita** [comment]
@NAMRATA-WOKE awesome thanks. I don't have access to their content. will ask if we can get a copy upfront.

**Comment by holanita** [comment]
For the time being, only the Linux Foundation has been promoting the course. To be discussed with Asim if we can put some efforts into this besides pushing the SOGS survey.

**Comment by holanita** [comment]
Okay, I've meant something different by external channels. I'll take all the ideas we had on the other tickets and this one from here and will map out the tasks one by one.

**Comment by holanita** [comment]
Closed and to be continued / discussed in the next meeting.
