### ISSUE TITLE
[Reference] Energy Efficiency: Energy proportionality

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/training#12]
There is an original paper by Google on this topic if I remember correctly, need to do some digging.

https://github.com/Green-Software-Foundation/training/blob/755ac252ae024be0c334cca2aaebade5d22d467b/docs/practitioner/energy-efficiency.md?plain=1#L67

**Comment by greenhsu123** [comment]
This "[The Case for Energy-Proportional Computing](https://research.google/pubs/pub33387/)" ?
