### ISSUE TITLE
Update the design of a google document (course exit page)

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#121]
What: @Jenya-design please tweak the design of [this document ](https://docs.google.com/document/d/1Jv-f7wGyODzEySQFfVk6Vo_OAHWjf-jAdFmyfDQUgvU/edit)a little bit. 
When: **by noon tomorrow (Nov 10)** as we should not be editing this document after the course goes live

It should be something very quick because we want to keep this really simple. Just need to apply some GSF design. If you don't have much time, just add something like a letterhead and that will do too.

If you have a bit more time, it would be nice to separate the top part from the rest. In this section we congratulate people for taking the course and tell them how to register for credits. We might have some more urls here in the future, for now we only have 1 bulletpoint.

**Comment by Jenya-design** [comment]
Hello @holanita 
Please allow me the edit access, I've sent the request

**Comment by holanita** [comment]
Done, sorry.

**Comment by Jenya-design** [comment]
@holanita please review

**Comment by holanita** [comment]
Looks perfect @Jenya-design thank you so much
