### ISSUE TITLE
[AFTER COP] Organize online events 

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#122]
What: organize short online events to explain and discuss each chapter of the course
Why: to promote the course, give insights and talk about each topic in detail
Where: we could use our Meetup platform for this and/or we could do very short LinkedIn lives (?)
When: sometime after COP

Content ideas for the events:
- [ ] Sarah/Asim/SME to briefly explain one chapter in each event
- [ ] Do an interview with an SME about a specific chapter or sub-topic
- [ ] Review and learn one chapter together in each event (similar to the idea discussed earlier)
- [ ] Do LinkedIn lives periodically about small sub-topics

Next step: 
- [ ] discuss the idea in our upcoming team meeting after COP and if approved:
- [ ] come up with a draft plan (how many events, where, what topics, who would be the host, participants, SMEs
- [ ] discuss the idea with Namrata and incorporate into marketing campaigns

**Comment by holanita** [comment]
TBD something similar for Patterns as well?

**Comment by holanita** [comment]
TBD in the community wg call tomorrow, as discussed in today's team meeting.

**Comment by holanita** [comment]
In today's Community WG call @tmcclell suggested to organize a meetup / online study session for Earth Day (April 22). Anne suggested we should target the Friday or the Saturday. Would a _day off_ work better for people?

**Comment by jawache** [comment]
Trending Event During Earth Week

**Comment by holanita** [comment]
Ok, will created a dedicated ticket for that and all other tasks.

**Comment by holanita** [comment]
Closed and to be continued here: https://github.com/Green-Software-Foundation/training/issues/142
