### ISSUE TITLE
Where do we draw the limit for embodied carbon?

### ISSUE THREAD

**Issue by gersanti** [Green-Software-Foundation/training#126]
Hi community,

While doing the [Green Software Development course](https://training.linuxfoundation.org/training/green-software-for-practitioners-lfc131/) it was interesting to learn about ways to account for the embodied carbon from a hardware piece, and this got me thinking...

One of the examples introduced the concept of SCI (Software Carbon Intensity), formula aside, it obtained by including the CO2 derived from Σ Energy consumed+embodied carbon (amortized) from the hardware peace where we are running our software. Although the explanation is on point and very clear, I feel we are falling short with the measurement, but I can be going way to deep.

If we consider the embodied carbon (and we must), shouldn't we also consider the amortized embodied carbon from the supporting equipment as well? (after all, HVAC, Racks, even lights have their own embodied carbon). Accounting for this would be challenge, I know, but it seems to me that it would be the only way to get the full picture (specially when looking at scope 3 emissions)

To make things more complicate, while analysing this... I thought about the embodied carbon from the energy sources as well. I noticed that most literature on the topic considers that the energy coming from green sources (such as solar farms, wind, nuclear, hydro, etc.) as CO2 free, however, those sources do have embodied carbon as well, not to mention the energy transmission footprint.

It appears that once this path starts, the rabbit hole never ends, but with no unified way to account for these values, it becomes very complicated to assess the footprint from a given DC, let alone compare properly between cloud providers to move workloads/infrastructure.

Is this something you had to deal with as well? Do you have some advice on where to draw the limit?

Kind regards to you all

**Comment by holanita** [comment]
Hi @gersanti thanks for your message. Adding @greenhsu123 and @jawache so they can review and comment.

**Comment by greenhsu123** [comment]
Hi, @gersanti; thank you so much for bringing this up! It's a great question, and I will answer it by linking you to another project that the Green Software Foundation's got going on- [the software carbon intensity specification](https://github.com/Green-Software-Foundation/software_carbon_intensity). 

The sections that I would like to bring to your attention are the [embodied carbon](https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/main/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md#software-boundary) section and the [software boundary section](https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/main/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md#software-boundary). Those two sections further explain the considerations you should have when considering embodied carbon for a software. Please let us know if those links suffice.
