### ISSUE TITLE
Review question in energy efficiency section

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#127]
@greenhsu123 @jawache I received this message from the LF. Let's discuss in the call today.

A learner mentioned in a survey that this question was confusing. Upon review, in the chapter "Energy Efficiency" under key concepts, it states that "Energy is measured in joules (J). Joules measure the volume of energy." Please review and let me know if a change needs to be made. Thanks!

https://github.com/Green-Software-Foundation/training/blob/27f17c6b3f2b4287a4d1c970f22613744534f1d1/docs/energy-efficiency.mdx?plain=1#L165

What unit measures volume of energy?
- Watts
- Kilowatts
- Kilowatt-hours

**Comment by holanita** [comment]
Energy measurement
Energy is measured in joules (J). Joules measure the volume of energy.
Watt (W) is a rate, corresponding to one joule per second.
A kilowatt (kW) is therefore also a rate, corresponding to 1000 joules per second.
A kilowatt-hour (kWh), is a measure of energy (J) corresponding to one kilowatt of power sustained for one hour.

**Comment by holanita** [comment]
might change to this on the website and in the LMS: a measure of **the volume** of energy
we should work on this section in the next version
@greenhsu123 to google this today/tomorrow

**Comment by holanita** [comment]
@greenhsu123 do you have any updates on this one? shall we proceed with the changes discussed last time and simply change the wording on the website and in the LMS?

current wording:
_A kilowatt-hour (kWh), is a measure of energy (J) corresponding to one kilowatt of power sustained for one hour._
new wording: 
_A kilowatt-hour (kWh), is a measure of **the volume of** energy (J) corresponding to one kilowatt of power sustained for one hour._

**Comment by greenhsu123** [comment]
I am proposing the following:

- Energy is measured in joules (J), the [SI](https://en.wikipedia.org/wiki/International_System_of_Units) unit of energy. 
- Power is measured in watts, where 1 watt (W) is a rate corresponding to one joule per second.
- A kilowatt (kW) is, therefore, also a rate corresponding to 1000 joules per second. 
- A kilowatt-hour (kWh) is a measure of energy (J) corresponding to one kilowatt of power sustained for one hour.

And we change the question to: "What is the SI unit of energy?" Answer: Joules

**Comment by holanita** [comment]
Thanks @greenhsu123 – @jawache please comment here in case you can't attend the call today. Thanks.

**Comment by jawache** [comment]
If @greenhsu123 is happy with it I'm happy with it :)

**Comment by holanita** [comment]
@greenhsu123 I've created a [PR](https://github.com/Green-Software-Foundation/training/pull/134) for you. Please review and merge. Thanks!

**Comment by holanita** [comment]
Closed as the PR has been processed. Thanks.
