### ISSUE TITLE
[Image] Carbon Awareness: Find original image

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/training#13]
This one is copied from the word doc

https://github.com/Green-Software-Foundation/training/blob/755ac252ae024be0c334cca2aaebade5d22d467b/docs/practitioner/carbon-awareness.md?plain=1#L65-L68

**Comment by holanita** [comment]
Closed my original issue to avoid duplicates. 
Folder with new images shared with Sarah. 
Images to be replaced: 01, 10, 22, 23

**Comment by greenhsu123** [comment]
this is completed.
