### ISSUE TITLE
Q&A – spare capacity of a public cloud provider

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#138]
@greenhsu123 we received this feedback in the course forum. We are supposed to reply within within 24 hours I believe, but I know you might be on holiday already. Please send me the response when you can and I'll add it to the forum.

I do think that it is a common (BIG) mistake to consider that the spare capacity of a public cloud provider is infinite. They MUST have an important spare capacity to fulfill their contractual obligations, and you do have special events generating a peak of demand that happen at the time for everyone in the world, like the Black Friday :-(
I think that the page [https://trainingportal.linuxfoundation.org/learn/course/green-software-for-practitioners-lfc131/hardware-efficiency/hardware-efficiency?page=1](https://forum.linuxfoundation.org/home/leaving?allowTrusted=1&target=https%3A%2F%2Ftrainingportal.linuxfoundation.org%2Flearn%2Fcourse%2Fgreen-software-for-practitioners-lfc131%2Fhardware-efficiency%2Fhardware-efficiency%3Fpage%3D1) should be corrected accordingly, especially the infinite sign on the second picture.

**Comment by greenhsu123** [comment]
@holanita, how about the below?

"Thank you for your feedback. It's an excellent point, and we agree that the public clouds do not have unlimited spare capacities. However, to conceptually demonstrate the difference between private and public clouds, where the latter gives you greater agility to scale up and down, the infinite sign serves its purpose in this context. We want to emphasise to our readers the potential capability the public clouds can give you during the peak capacity compared to the finite capacity a private cloud can offer."

**Comment by holanita** [comment]
Feedback sent. Case closed. Thanks.
