### ISSUE TITLE
[Reference] Carbon Awareness: Impact

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/training#14]
There is an original paper from Conor Kelly at Microsoft which is where those numbers come from. There are however others that have now been created since with differing numbers, let's do a search and find them and put them in.

https://github.com/Green-Software-Foundation/training/blob/755ac252ae024be0c334cca2aaebade5d22d467b/docs/practitioner/carbon-awareness.md?plain=1#L112-L114

**Comment by greenhsu123** [comment]
original paper- https://ieeexplore.ieee.org/document/6128960
