### ISSUE TITLE
06_energy_proportionality.png graph inaccuracy and typo correction

### ISSUE THREAD

**Issue by sebhulse** [Green-Software-Foundation/training#141]
**Describe the bug**
The graph in the image `06_energy_proportionality.png` on the page [https://learn.greensoftware.foundation/energy-efficiency](https://learn.greensoftware.foundation/energy-efficiency) displays `Uttilization` (x axis)  against `Energy` (y axis). Given the definitions of energy and power [further up the page](https://learn.greensoftware.foundation/energy-efficiency#energy-measurement), I believe the graph should instead show `Utilization` (x axis)  against `Power` (y axis) - not Energy. Energy is a measure of power over time (J or Wh) whereas the graph appears to show instantaneous power consumption (J/s or W). There is also a typo on the word `Utilization` - it shows `Uttilization` instead of `Utilization`.

**To Reproduce**
Go to [this page](https://learn.greensoftware.foundation/energy-efficiency) and scroll to the `06_energy_proportionality.png` image/graph. 

**Expected behavior**
A graph of `Uttilization` against `Energy` is shown, whereas a graph of `Utilization` against `Power` should instead be shown.

**Comment by holanita** [comment]
@sebhulse thanks for your comment. 
@greenhsu123 pls review when you are back after the holidays.

**Comment by greenhsu123** [comment]
@sebhulse- Thank you for the above and great catch! 

@holanita - as described, could we please ask the designer to update this [image](https://learn.greensoftware.foundation/assets/images/06_energy_proportionality-26f4b3b1bd18a477a3738dad74dfe3aa.png). ?

1. update the Y-axis's heading from "energy" to "power." 
2. correct the spelling of the X-axis's heading to "utilization."

**Comment by holanita** [comment]
A new ticket has been created. Our designer is on holiday atm. We'll update the image as soon as possible.

**Comment by holanita** [comment]
This has been fixed: https://learn.greensoftware.foundation/energy-efficiency/#energy-proportionality
