### ISSUE TITLE
Remove certification from social media posts 

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#149]
Hi @NAMRATA-WOKE the LF just reached out because of a misleading post that says people can get certified. See the attached screenshot. Our course is a training course and learners get a proof of completion (badge and certificate of completion) after completing the course. But we are not certifying them in anything.

We were not supposed to use this term in the course and in the book of news – and similarly, we shouldn't use it in our marketing materials and posts either. Can you please update all the posts that mention the word certification or give the hint that people can get certified. Get Certified could be changed with something like Enroll Today, and the "get certified in green software" phrase can be updated to say something like "learn about green software" or something along these lines.

<img width="983" alt="Screenshot 2023-01-04 at 13 44 50" src="https://user-images.githubusercontent.com/100846607/210557529-ff7cb704-0ce6-4673-8a2e-fc7a2eedf88d.png">

**Comment by NAMRATA-WOKE** [comment]
Thanks - will remove and publish another post with approved language.
