### ISSUE TITLE
[Misspelling] Carbon Efficiency: Greenhouse gasses and the greenhouse effect

### ISSUE THREAD

**Issue by camcash17** [Green-Software-Foundation/training#15]
I believe the heading is misspelled as the word 'gases' should only contain two "S's".

https://github.com/Green-Software-Foundation/training/blob/755ac252ae024be0c334cca2aaebade5d22d467b/docs/practitioner/carbon-efficiency.md?plain=1#L37

**Comment by ccasher** [comment]
Another argument for single 's': On the https://ghgprotocol.org/ website, if you go for a global search of 'gasses' there are zero results.

**Comment by holanita** [comment]
thanks @ccasher it is now confirmed that we are going to go for gases instead of gasses. see [here](https://github.com/Green-Software-Foundation/training/issues/35)
