### ISSUE TITLE
Update image in the training

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#152]
Hi @Jenya-design please update this [image](https://learn.greensoftware.foundation/assets/images/06_energy_proportionality-26f4b3b1bd18a477a3738dad74dfe3aa.png) as follows:
- update the Y-axis's heading from "energy" to "power."
- correct the spelling of the X-axis's heading to "utilization."

**Comment by Jenya-design** [comment]
Hello @holanita 
Sure, I'll update as soon as I'm back on Jan 13

**Comment by holanita** [comment]
Thanks, see you next week!

**Comment by Jenya-design** [comment]
Hello @holanita 
I attach the update here
related images are also updated in the 3 folowing folders
https://drive.google.com/drive/folders/1n4Fe1_SXgpmUXIzj9_wLjQAIpjP7gfn2?usp=share_link
https://drive.google.com/drive/folders/1n5EWIDirRJBDOuPxhiNPSB0bvCf1ZT-Z?usp=share_link
https://drive.google.com/drive/folders/1GzKBOl2RWDi0TSCVG-AgwlZ5oHM8cdGC?usp=share_link

![Image](https://user-images.githubusercontent.com/69306070/212351206-01192076-cbb8-4a57-b0b3-b2023869de37.png)

**Comment by holanita** [comment]
Wonderful thanks a lot @Jenya-design ! I figured this image was used [in this deck](https://docs.google.com/presentation/d/14Ii4VINo2-cCbBYzn31F0zvyyEgM5y5MlVPrEihcf5A/edit#slide=id.gf452f625d9_1_0) so I've replaced it there too.
