### ISSUE TITLE
Create banner for homepage to promote the training

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#154]
Hi @Jenya-design when you are back, could you create a homepage banner to promote the course? This will replace the SOGS banner that we added last year and should have a similar layout.

- Design: I'll leave the details up to you. 
- Text: Learn how to build, maintain and run greener applications
- CTA: Take our course
- Green Software for Practitioners Course (add this text only if it fits into the layout. feel free to skip this if it doesn't!)

**Comment by Jenya-design** [comment]
Thank you @holanita 
banner will be linked with [this page](https://learn.greensoftware.foundation)?

**Comment by holanita** [comment]
Yes!

**Comment by Jenya-design** [comment]
Hello @holanita 
Please check two options for the banner and let me know what you think
I made the design very simple as I saw that SoGS banner was simplified. I assume Osama made it for adativity
All files (including svg [here](https://drive.google.com/drive/folders/1iPm0eufNV1hGfQSzRTcCqQZKUtt2X5hH?usp=share_link))


![Image](https://user-images.githubusercontent.com/69306070/212749607-15b32940-ed74-4f5e-9927-ee0f8c16b2f2.png)


![Image](https://user-images.githubusercontent.com/69306070/212749616-7d9401f1-02fd-45fb-84a1-eadc2c8da053.png)

**Comment by holanita** [comment]
Perfect, thanks a lot @Jenya-design I've asked Osama to add this to the website.
