### ISSUE TITLE
Replace principle link in the main menu

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#155]
Hi @osamajandali we have a menu item in the dropdown that leads to Principles. See the attached screenshot. 
This still leads to the old principles page that is now outdated: https://principles.green/
Could you please replace that link with this new one: https://learn.greensoftware.foundation/

(Note that we might make further changes later, but this is just a quick fix to avoid that traffic goes to the wrong place.)

<img width="1336" alt="Screenshot 2023-01-16 at 19 39 20" src="https://user-images.githubusercontent.com/100846607/212746720-b7f54725-6e09-43ff-932b-c35de406aa16.png">

**Comment by osamajandali** [comment]
Done

**Comment by holanita** [comment]
Great thanks @osamajandali
