### ISSUE TITLE
Add new website banner to promote the training

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#156]
Hello @osamajandali please add a new banner to the website.

The banner should lead users to [this page](https://learn.greensoftware.foundation/) to promote the course. All files including svg can be found [here](https://drive.google.com/drive/folders/1iPm0eufNV1hGfQSzRTcCqQZKUtt2X5hH?usp=share_link). Use the one with the blue background, marked as _final_. I'm attaching a preview below just in case. Thanks!

![preview](https://user-images.githubusercontent.com/100846607/212830053-50e9be12-d782-4f51-9939-5c6362180288.png)

**Comment by holanita** [comment]
That's ok. Pls just change the target url as it still takes me to the survey. It should be: https://learn.greensoftware.foundation/

**Comment by osamajandali** [comment]
Done

**Comment by holanita** [comment]
Thank you!
