### ISSUE TITLE
2022 08 16 - Green Software Principles Agenda

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#18]
## Date
2022-08-16 - 3pm UTC - See the time in your timezone https://everytimezone.com/s/a8399b00

## Agenda
- [x] Education WG / becoming a sub-working group
- [x] Discussing updates and issues

## Decisions Made
The team review period has been extended until August 26.

The Education WG will not be launched for now. We'll revisit this right before or after COP. Ideas about future projects and acitvities: workshops, content/knowledge sharing, university level groups like MSLA, student ambassador programs, etc.

## Actionable Items 
- [x] (Anita) Send reminder to the team that we have extended the team review period with another week 
- [ ] (Asim/Osama) Rename subdomain to http://learn.greensoftware.foundation/ instead of training...
- [ ] (Asim/Osama) Update project pages and urls here: https://greensoftware.foundation/projects
- [ ] (Asim/Osama) Update urls here: https://greensoftware.foundation/projects/principles-of-green-software-engineering
- [ ] **Added after the meeting:** (Anita) add text to images: Creative Commons - Green Software Foundation -greensfotware.org

## Pending Items from previous meetings
- [ ] (Sarah/GSF) to review all issues
- [ ] (Sarah) to add the updated images
- [ ] (Asim/Osama) Double check how 'toggle' could work for Q&A (won’t be visible on the website only on GitHub) 

## Future plans
- [ ] Email org leads once the consistency review has started as suggested by Tammy on Aug 17 in the WG call
- [ ] (Asim/Osama) Early September - share the Github stats with the list of active contributors 
- [ ] (Asim/Osama) Early September - tidy up list of contributors on the website
- [ ] (Anita) Early September - revisit milestones to make sure we hit the final deadline (COP)
- [ ] (Asim, Tammy) define scope and launch the Education WG (workshops, content sharing, university level groups like MSLA, student ambassador programs, etc.)
- [ ] **In the Community WG call held on Aug 17,** Daniel Vaughan suggested to organize study groups on Meetup where people could study and prepare together for the certification (maybe 4x1 hours sessions)

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

### Attendees
**Bill J., Sarah H., Akshit B., Cameron C., Markus S., Tammy M. + Anita H.**

**Comment by ccasher** [comment]
Attended

**Comment by jawache** [comment]
Attended

**Comment by greenhsu123** [comment]
Attended

**Comment by akshitbatra** [comment]
Attended.

**Comment by holanita** [comment]
Attended – action items have been updated to include new items, pending ones from previous weeks and future plans

**Comment by holanita** [comment]
Updated - added 1 future plan based on the WG call and discussions w/Asim
