### ISSUE TITLE
[Reference] Climate Commitments: Abatement

### ISSUE THREAD

**Issue by greenhsu123** [Green-Software-Foundation/training#24]
Link abatement to a good external definition or paper. 
https://github.com/Green-Software-Foundation/training/blob/f6a171996e813584b3217dc3a5c6062ecd01c400/docs/practitioner/climate-commitments.md?plain=1#L29

**Comment by jawache** [comment]
I've been looking at this and I'm starting to get worried that my definition of abatement doesn't exactly match the definition of elimination. 

Also it's a little confusing having two terms, one set are the old terms and one set are the new terms, think it adds clarity to just have one set of terms.

Elimination
Removal
Avoidance

The definitions for all of those are clear and those are the modern terms.

**Comment by jawache** [comment]
Really struggling to find a good definition, it's just used like the word "and" and the dictionary definitions relate more to it's use in the finance.

The best doc describing it I can find is this PDF, it's fairly short will just link to this. https://sciencebasedtargets.org/resources/legacy/2020/09/foundations-for-net-zero-executive-summary.pdf
