### ISSUE TITLE
[Reference] Climate Commitments: Compensating / Carbon Avoidance

### ISSUE THREAD

**Issue by greenhsu123** [Green-Software-Foundation/training#28]
https://github.com/Green-Software-Foundation/training/blob/9d84b51fd0f33ae7e085cf45d3b26032ca030664/docs/practitioner/climate-commitments.md?plain=1#L49

**Comment by greenhsu123** [comment]
https://www.goethe.de/en/kul/ges/21621622.html?

**Comment by holanita** [comment]
https://www.abatable.com/blog/carbon-removal-vs-carbon-avoidance-projects
