### ISSUE TITLE
[Reference] Climate Commitments: Neutralizing / Carbon Removal

### ISSUE THREAD

**Issue by greenhsu123** [Green-Software-Foundation/training#29]
https://github.com/Green-Software-Foundation/training/blob/9d84b51fd0f33ae7e085cf45d3b26032ca030664/docs/practitioner/climate-commitments.md?plain=1#L59

**Comment by greenhsu123** [comment]
https://brc.org.uk/climate-roadmap/section-4-pathway-1-placing-greenhouse-gas-data-at-the-core-of-business-decisions/415-offsetting-and-carbon-removals/

**Comment by holanita** [comment]
https://www.abatable.com/blog/carbon-removal-vs-carbon-avoidance-projects
