### ISSUE TITLE
[Spelling] Double check gasses vs. gases with editor & update content

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#35]
Checking with editor
These links seem to support the argument that gasses is related to the verb rather than the noun.
https://www.merriam-webster.com/dictionary/gas 
https://grammarist.com/usage/gases-gasses/
https://www.dictionary.com/e/gases-or-gasses/

**Comment by holanita** [comment]
@greenhsu123 @jawache @dubrie the editor conformed that we should use gases instead of gasses. how shall we proceed with these updates? happy to help if you can explain me the steps.

**Comment by ccasher** [comment]
Further confusion about the spelling from a google docs suggestion

<img width="441" alt="Screen Shot 2022-09-02 at 7 53 50 AM" src="https://user-images.githubusercontent.com/62668140/188164463-d2d5482c-8447-4d2b-aa4d-eec1ae7d1c9e.png">
