### ISSUE TITLE
2022 08 09 - Green Software Principles Training Agenda

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#5]
## Date
2022 08 09 - 1.30pm UTC - See the time in your timezone https://everytimezone.com/s/a8399b00

## Agenda
- [x] Tracking agendas and attendance in Github
- [x] Review recently submitted issues (change requests), if any – none
- [x] Tidy up list of contributors on the website
- [x] Discuss Q&A

## Decisions Made
Within a month we will get the list of active contributors based on GitHub stats and will then add them to the website

## Action Items closed shortly after the meeting
- [x] (Sarah) Archive old repo 
- [x] (Anita) Add an issue for anyone to comment if they don’t have any specific change requests 
- [x] (Anita) Send a reminder to team members to review content and add issues or comment on generic issue 
- [x] (Sarah, Anita + Asim) Review content to identify any missing parts (XXX) or links and add issues accordingly 
- [x] (Anita) Follow-up on becoming a sub-working group of the Community WG 
- [x] (Anita) Ask designer to share missing images + add issue 

## Action Items to be tracked in future agendas
- [ ] (Asim/Osama) Double check how 'toggle' could work for Q&A (won’t be visible on the website only on GitHub) 
- [ ] (Asim/Osama) Within a month share the Github stats with the list of active contributors 
- [ ] (Asim/Osama) Tidy up list of contributors on the website

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
**Complete list of attendees: Asim, Cameron, Sarah, Tammy + Anita**

**Comment by jawache** [comment]
Attended

**Comment by tmcclell** [comment]
Attended

**Comment by greenhsu123** [comment]
Sarah Hsu, Goldman Sachs, [greenhsu123](https://github.com/greenhsu123)

**Comment by holanita** [comment]
Attended

**Comment by holanita** [comment]
Closed. Pending items have been added to the current meeting agenda & memo.

**Comment by holanita** [comment]
Closed. Pending items have been added to the current meeting agenda & memo.
