### ISSUE TITLE
[Consistency Review] Green Software Practitioner Training 

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#61]
Consistency Review - In this phase, the Green Software Practitioner Training developed by the Principles of Green Software Engineering Project Team within the Community WG will be formally reviewed by the GSF members. After this period, the Project Team and the Working Group will address any submitted issues received prior to formally approving it for public release.

The training can be reviewed on this page: https://learn.greensoftware.foundation/practitioner/introduction
Comments may be submitted in this issue or as a separate [issue](https://github.com/Green-Software-Foundation/training/issues).

NOTE: All comments must be submitted by 22 September.

**Comment by PindyBhullar** [comment]
Reviewed the practitioner training, and it's very comprehensive and easy to understand. I would be happy to promote the training at UBS. Thank you for all your efforts.

**Comment by holanita** [comment]
@PindyBhullar thank you very much for your feedback. The training will be officially announced at COP27 in early November. Please stay tuned as we will be sharing all the relevant updates in this repo and in our communication channels.

**Comment by holanita** [comment]
Consistency Review Closed - No further comments to be added
