### ISSUE TITLE
[Quiz] New questions requested by the LF

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#71]
We should add 3 more questions to the content as there will be short quizzes at the end of each chapter as well, not just at the end of the course. Can we add them at this point?

***

Energy Efficiency:

**What unit do we use to measure energy efficiency?**
Joules
Watts
Kilowatt-hours*

**Choose the most energy efficient option:**
An application that consumed 10kWh in a data centre with a PUE of 1.5
An application that consumed 15kWh in a data centre with a PUE of 1.2
An application that consumed 20kWh in a data center with a PUE of 1
(editor: suggest adding this in the final quiz and Qs4 and 5 in end-of-chapter, otherwise it gives a hint)
confirm correct answer

Hardware Efficiency:

**Why is moving operations to the public cloud more energy efficient overall? (more than one option is possible)**
Because using the public cloud reduces your emissions
Because using the public cloud allows you to re-architect your software in order to reduce your emissions*
Because the public cloud makes better use of spare capacity*

**Comment by holanita** [comment]
Confirmed in today's ops call that we can add 3 more questions as long as the core course content remains the same. Actual questions and answer options to be discussed and confirmed in today's call

**Comment by holanita** [comment]
@greenhsu123 did you guys process this one? I can't seem to find the PR or the updates. 

I've added these questions to my files (US spelling):

**What unit measures volume of energy?**
Watts
Kilowatts
Kilowatt-hours*

**Which application consumes the most energy?**
An application that consumes 10kWh in a data center with a PUE of 1.5
An application that consumes 15kWh in a data center with a PUE of 1.2
An application that consumes 20kWh in a data center with a PUE of 1

**Comment by holanita** [comment]
@greenhsu123 @jawache in the 2nd question we now have two answers marked as true. is the third one the correct one?

https://github.com/Green-Software-Foundation/training/blob/0dffce7e7419ebf9e031be2d40870ae7176e1892/docs/practitioner/energy-efficiency.mdx?plain=1#L147

question:
        "Which application consumes the most energy?",
      answers: [
        {
          text: "An application that consumes 20kWh in a data center with a PUE of 1",
          isCorrect: true,
        },
        {
          text: "An application that consumes 15kWh in a data center with a PUE of 1.2",
          isCorrect: false,
        },
        {
          text: "An application that consumes 10kWh in a data center with a PUE of 1.5",
          isCorrect: true,
        },
      ],

**Comment by greenhsu123** [comment]
apologies, fat finger mistake

**Comment by holanita** [comment]
no worries thanks @greenhsu123
