### ISSUE TITLE
[Carbon efficiency] Carbon and CO2eq

### ISSUE THREAD

**Issue by greenhsu123** [Green-Software-Foundation/training#77]
https://github.com/Green-Software-Foundation/training/blob/ac62ddf2f053363fc78b361928523801d635b955/docs/practitioner/carbon-efficiency.mdx?plain=1#L44

We should mention CO2e somewhere in this paragraph, so it's consistent with quiz #2

**Comment by holanita** [comment]
@greenhsu123 during the final review of the content I noticed we never used <sub>, we use CO2 consistently throughout the content. That's the format I'll submit to the LF.

**Comment by greenhsu123** [comment]
i think we should mention all 3 as they are all equivalent as described in the glossary https://learn.greensoftware.foundation/practitioner/glossery

**Comment by greenhsu123** [comment]
p.s we have already addressed this in a [PR ](https://github.com/Green-Software-Foundation/training/pull/81)and it's been merged in https://learn.greensoftware.foundation/practitioner/carbon-efficiency#carbon-and-co2eq

**Comment by holanita** [comment]
@greenhsu123 what I meant is that we never used subscript in the content before (I referenced the html element by accident and it messed up my original message). so I changed your subscripts to CO2 in the google docs. can you please fix this in the code?
