### ISSUE TITLE
[Hardware Efficiency] - Quiz 7 has the wrong phrasing for the answer

### ISSUE THREAD

**Issue by greenhsu123** [Green-Software-Foundation/training#78]
https://github.com/Green-Software-Foundation/training/blob/ac62ddf2f053363fc78b361928523801d635b955/docs/practitioner/hardware-efficiency.mdx?plain=1#L194

Shouldn't this be- embodied carbon often accounts for more emissions than the emissions from the electricity powering the device

**Comment by holanita** [comment]
@greenhsu123 I'm closing this as the corresponding PR was merged yesterday
