### ISSUE TITLE
[Climate Commitment] Quizz

### ISSUE THREAD

**Issue by greenhsu123** [Green-Software-Foundation/training#79]
https://github.com/Green-Software-Foundation/training/blob/ac62ddf2f053363fc78b361928523801d635b955/docs/practitioner/climate-commitments.mdx?plain=1#L295

Should we change the question to "What is the "primary" goal with abatements?"

**Comment by holanita** [comment]
@greenhsu123 I'm closing this as the corresponding PR was merged yesterday
