### ISSUE TITLE
[Missing figures] Hardware Efficiency: replace XX with correct figures

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#8]
This line contains 4 pieces of missing content marked by XX. We need to do some research to find the correct information and replace these.

https://github.com/Green-Software-Foundation/training/blob/755ac252ae024be0c334cca2aaebade5d22d467b/docs/practitioner/hardware-efficiency.md?plain=1#L31

**Comment by greenhsu123** [comment]
The paper were the graph was from- https://www.ifi.uzh.ch/dam/jcr:fa4e956e-7a53-4038-98a5-00e09e2f4303/Study_Digitalization_Climate_Protection_Summary_Oct2017.pdf
