### ISSUE TITLE
[Review & Testing] Q&A

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#84]
@jawache @greenhsu123 @dubrie based on recent conversations about wrong and/or new questions, I'd suggest we perform a careful final review of the Q&A. it's not urgent, let's wait for the LF to set up everything first. we can send them all the change requests in one go when we do the final review & testing. I'll just leave this here as a reminder.

**Comment by jawache** [comment]
Everyone agreed to this approach on the call. Wait for LF final version and then do a final review.

**Comment by holanita** [comment]
The setup was completed last week by LF. I reviewed the entire course and requested some changes and fixes which are all done now. Anybody can take a look at the entire course including the Q&A [here](https://docs.google.com/presentation/d/1QJLv_tPb6dx1jXxIUwJqaXLqhEFvsb_u7qiODwoWhkc/edit?usp=sharing). I suggest we discuss the Q&A in this week's call.

**Comment by holanita** [comment]
Discussed in today's call. Review to be finished by the end of the week. Comments are welcome by Friday COB.

**Comment by holanita** [comment]
Next steps: confirm final changes with Asim, share with LF today, process updates in repo as well.

**Comment by holanita** [comment]
https://github.com/Green-Software-Foundation/training/pull/112 processing necessary updates

**Comment by holanita** [comment]
processed on Friday. course updated by LF today. closing this as the course is finalized and will go live today.

**Comment by holanita** [comment]
We have received feedback from @navveenb today. As this ticket has been closed already and we don't have much time before go live, I recommend we skip these updates, but let's keep in mind for future courses.

Navveen: Learners have the option to take the assessment without even going through the content – I assume this is possible as we were able to complete the assessment directly. 
Anita: I think this should be fine. The course is set up according to LF best practices.

Navveen: 30 questions for foundational training seems too high as per our standard learning practices. Would recommend having no more than 15 questions based on our existing training experience. 
Anita: This is not a minor update and I am afraid it is too late to change this. The knowledge checks and the final exam have all been set up in line with the LF team's recommendations and best practices.

Navveen: Question-answer format should be “single correct response” questions; meaning people should not be given the option to select multiple options, although there is only one right answer. 
Anita: There is always just one correct answer. Waiting for further explanation from Navveen via email.

**Comment by holanita** [comment]
Progress after today's team meeting: the Linux Foundation will 
- [ ] update their default settings to allow one answer per question only in each case
- [ ] review each question to make sure everything is set up correctly
- [ ] remove 10 questions from the final exam to make it shorter or easier to pass

Also, they will
- keep the passing grade at 85% and users will still be able to take the quiz as many times as needed
- NOT be able to share detailed drop off rates just the following data: total enrollments, total completions, enrollments over the past 7 days, completions over the past 7 days

**Comment by holanita** [comment]
All the updates are done. There were no bugs, they just made some adjustments as we were not happy with their default settings. Tested. Closed.
