### ISSUE TITLE
[Review & Testing] Comments during Code Freeze

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#85]
@jawache @greenhsu123 @dubrie I'd suggest we announce code freeze once the pending issues and PRs are closed. can we use this issue to collect further comments and change request, if any? I'd like to focus on working with the LF on the setup in the upcoming weeks. we can do a final round of change requests later in one go if you all agree.

**Comment by jawache** [comment]
Sounds great to me!

**Comment by jawache** [comment]
@dubrie we'll hold off merges for now but people can still propose. 

After @greenhsu123 merges the two pending PRs we will change the settings on this repo to not allow merging.

**Comment by holanita** [comment]
LF suggested some changes during the setup of the online course. See in this PR: https://github.com/Green-Software-Foundation/training/pull/99. I'm not aware of any other issues, comments, PRs raised during 'code freeze'.

**Comment by holanita** [comment]
assigned Sarah as reviewer to all 3 open PRs

**Comment by holanita** [comment]
processed on Friday, no more open prs left. closing this as the course is finalized and will go live today.
