### ISSUE TITLE
[Broken link] Measurement - case studies

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#87]
https://github.com/Green-Software-Foundation/training/blob/86c54af35dc3117e96bd45bf9ccefc032e1a99d3/docs/practitioner/measurement.mdx?plain=1#L142

@osamajandali @jawache looks like [this page](https://standards.greensoftware.foundation/case-studies/) disappeared recently (page not found). can you recover the content?

**Comment by jawache** [comment]
Oh wow, this actual work was never actually done by the standards working group. Can you just delete the whole line? @holanita

**Comment by jawache** [comment]
PR merged so we can close.
