### ISSUE TITLE
[Website] Create training exam completion landing page

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#89]
After a user completes our course, they will be taken to a landing page. We need this for C2As and to collect user data. Details to be discussed in October.

C2As for those who completed the course:
- sign up for newsletter
- join meetup

Data to be collected from users:
- email address
- name
- company name

- [ ] update https://grnsft.org/practitioner-training/lf-post-exam-redirect to point to the correct page on GSF

**Comment by jawache** [comment]
Team: Concerns regarding GDPR and storing personal data. One idea is to speak to the LF about using their internal systems for collecting and sending the information above that way we use their GDPR thing.

**Comment by holanita** [comment]
From our conversation with Asim today, it might be time now to start working on this task. Please keep this thread updated.

**Comment by holanita** [comment]
As discussed with Asim today, this should be a very simple page. Just asked him to review the copy for this [in this issue](https://github.com/Green-Software-Foundation/training/issues/101).

@zanete I would need to send the url to LF asap as soon as the copy is done. Do you think Osama could at least create a blank page for this so I can share the url? Or would it make sense that you create a generic url for this one as well until we have the final one?

**Comment by zanete** [comment]
Clarified with @jawache that he can do this via the CMS (no need to involve any actual web dev) and the link will be https://grnsft.org/practitioner-training/lf-post-exam-redirect (need to remember to update the short link after the page has been created).

**Comment by holanita** [comment]
@zanete I am aware that Osama is working on SOGS now. Just wanted to check if you have an ETA for this? This is currently added to the sprint [Oct-31].

**Comment by zanete** [comment]
@holanita so far there is no reason to believe that it will not be done this week. Is there a specific date that you would need this by?

**Comment by holanita** [comment]
@zanete ok I see. I just wanted to make sure we don't forget about this. thanks :)

**Comment by holanita** [comment]
@zanete just to clarify, does the date indicate the due date or the start of the sprint?

**Comment by zanete** [comment]
@holanita the Sprint is the Monday of the week, and there is no currently due-date set for this, but I have booked some time with Asim tomorrow to go through this. Will that be ok? I will let you know if anything changes in his schedule.

**Comment by zanete** [comment]
@holanita Asim will do all training website things Friday morning
cc @jawache

**Comment by jawache** [comment]
@holanita i've created a pull request with everything in it here https://github.com/Green-Software-Foundation/training/pull/115

Sarah or someone else should do a quick review before accepting.

**Comment by holanita** [comment]
@jawache I can't figure out how to find the landing page in the PR. Got lost in the code. We need a landing page for those who completed the course – is this the one you have in the PR? 

Also, Navveen just told me that they are working on creating their form for users to log their certificate of completion. This should be added to the landing page. ETA is Nov 8. Told him I'm not sure we'll have time to add this just before COP.

**Comment by holanita** [comment]
@jawache @zanete can you help me find the new landing page? I can't figure out the new url. maybe it hasn't been craated yet because of a misunderstanding. note that this ticket is not the same as #111

**Comment by zanete** [comment]
@holanita I have asked Asim to let us know how we can review before it's merged. He will spend some time today on this.

**Comment by jawache** [comment]
Sorry I commented on the wrong ticket, I've changed the name of this to "[Website] Create training exam completion landing page" we've not created that yet. 

Need to create a page on our CMS, DatoCMS. 

@holanita if you can give us the exact copy that should appear on that page that would be best

**Comment by holanita** [comment]
@jawache sure see below the approved copy. Feel free to adjust as needed. As I mentioned above, Navveen has started creating Accenture's form. Waiting for the url. So what I'd suggest is that you set up a simple page with the copy below and when Navveen's form is available, I'll replace the last line with 'Accenture' and a link to the form. I'll do the same every time we receive a new form.

***

Congratulations for successfully completing our course. See below the organizations which have created forms to facilitate the administration of credits for completing this course. If your organization would like to add their form here, please get in touch with our team at help@greensoftware.foundation. 

If you wish to find out more about our foundation and/or get involved, we invite you to
[sign up for our newsletter](https://grnsft.org/newsletter)
[join our local meetup group(s)](https://www.meetup.com/pro/gsf/)

- Currently there are no available forms

**Comment by zanete** [comment]
@jawache if you paste here a link to the CMS, maybe I can figure out how to add that page?

**Comment by holanita** [comment]
As discussed in the call today, we might use a google doc instead. Setup in progress. We have received Accenture's url.

**Comment by zanete** [comment]
@holanita That's done now, does it mean can we close this task? or will this be updated in the future?

**Comment by holanita** [comment]
@zanete just tested this (including exit from the course). we can consider this done imo
