### ISSUE TITLE
[COP] Announce the training & patterns

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/training#97]
@greenhsu123 this is just to make sure you have all the information you need to be able to announce the the training at COP

To be confirmed by Sean (updated on Oct 24th): 
- [x] dry run scheduled for Nov 4
- [x] Approx time of the announcement during the live event will be from 1000-1020 PST/1800-1820 GMT
- [x] Deck: GSF staff are creating a ppt deck for the whole event. This should be available by the end of this week.
- [x] Format: The event will be a mix of live and pre-recorded material 
- [x] Streaming: https://decarb.greensoftware.foundation/
- [x] Hackathon: Winner announcements will be live, with pre-recorded material to demonstrate the project.
- [ ] Sarah: Does a government official have a role at the event? (i.e speaking, sponsor?)

**Comment by greenhsu123** [comment]
How long would the annoucement be? And could you share the agenda for the event?

**Comment by holanita** [comment]
As far as I know the announcement would be 8 min (principles & patterns combined). 
Let me ask Sean to reach out to you and confirm all the details.

**Comment by holanita** [comment]
Deck to be shared with Sarah and Bill as soon as finalized by the ops team

**Comment by holanita** [comment]
@greenhsu123 
- if you only share our own website during COP, pls also mention there is a page where they can take the course & exam
- [this is the url](https://training.linuxfoundation.org/training/green-software-for-practitioners-lfc131/) of the enrollment page where they can take the course and the exam
- this has been added to the speaker notes in the deck
- plus the new button on our website will take users to the same page

@dubrie 
- for patterns we just need to share our own website I guess
- would be nice to remind them of the 'add/edit patterns' button at the top so they know how to contribute

As far as I know, the deck will be finalized today so I'll share with you guys the most up-to-date version sometime tomorrow.

Let me know if you need anything else.

**Comment by greenhsu123** [comment]
Thanks so much for the above @holanita!

**Comment by holanita** [comment]
You're welcome and good luck! Deck locked and shared.

**Comment by holanita** [comment]
@dubrie since Asim suggested yesterday that we might change the review process a bit compared to what we had planned, it would be best not to mention that we will be publishing patterns on a quarterly basis. just don't mention the frequency. encourage them to submit new patterns any time they have a new idea. what do you think?

**Comment by holanita** [comment]
Great job @greenhsu123 @dubrie thank you and let's continue next week :)
